---
title: "CASE STUDY TITLE"
author: "Exode"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, include = FALSE}
library(car)
library(mosaic)
library(pander)
library(scatterplot3d)
library(plotly)
library(ggplot2)
library(tidyverse)
library(DT)
library(broom)
library(ourworldindata)
```

```{r include=FALSE}
devtools::install_github("drsimonj/ourworldindata")
```
```{r}
child_mortality
```

```{r include=FALSE}
death <- read_csv("C:/Users/exoni/Downloads/annual-number-of-deaths-by-cause.csv")
```

```{r}
d <- select(death, everything())
```


```{r}
rate <- child_mortality
rate %>% 
  filter(year >= 1957 & !is.na(continent)) %>%
  group_by(continent, year) %>% 
  summarise(child_mort = sum(child_mort, na.rm = TRUE)) %>% 
ggplot(aes(x = year, y = child_mort, color = continent)) +
    geom_point() +geom_line()+ facet_wrap(~continent,nrow=1)+
    theme_dark() + scale_color_manual(values = c("black","pink","gray","purple","violet"))+
    labs(
      title = "Child Mortality by Continent and by Year",
      x = "Year",
      y = "The Number of Children dying before the age of 5 years (per 1,000 births)"
    )
```


```{r eval=FALSE, include=FALSE}
```


```{r eval=FALSE, include=FALSE}
library(maps)
data <- read.csv("C:/Users/exoni/Downloads/child-deaths-igme-data.csv")
```
```{r eval=FALSE, include=FALSE}
dataplot<-geom_map(map.data) + 
                 geom_point(data = data,aes(x = Year, y = `Number of under-five deaths`), alpha = 1, fill = "red", pch = 21, size = 6) + 
                  labs(x = 'Longitude', y = 'Latitude') +
                  geom_dl(data = data, 
                      aes(label = labels), 
                      list(dl.trans(y = y + 0.3), "boxes", cex = .8, fontface = "bold"))
```
```{r}
ggsave("Task5b.png")
```


I am trying to reproduce a graph from []https://ourworldindata.org/child-mortality
The graph shows how the number of deaths for children under 5 years has been changing between 1990 and 2017

```{r}
data <- read.csv("C:/Users/exoni/Downloads/child-deaths-igme-data.csv")
da <- filter(data,Year>=1990)
dat <- da %>% group_by(Year) %>% summarise(World=sum(deaths))
dat$World <- dat$World/1000000
P <- ggplot(dat)+geom_line(aes(Year,World),color="blue",size=1)+geom_point(aes(Year,World),color="blue",size=3)+labs(y= "Number of Deaths in the World(in millions)",title="Number of Child Death, 1990-2017. \n Number of Deaths of children under 5 years old.")+theme_bw()

ggplotly(P, tooltip=c("World","Year"),width = 1000, height = 600) %>%
    animation_opts(17)
```

```{r}
ggsave("Task5b.png")
```
